### ISSUE TITLE
Banner css issue

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-elemental-blocks#30]
Hi
I'm having an issue with the default banner css in firefox (57.0.1) and Safari (9.1.2), theme simple. 

**Opera/Chrome** seem to be fine (not tested in explorer):
![afbeelding](https://user-images.githubusercontent.com/614243/33717352-dfc37b4a-db59-11e7-93d6-aaf0b888b115.png)

**Safari** - the content seems to be located underneath/to the right of the banner-image
![afbeelding](https://user-images.githubusercontent.com/614243/33717234-729536bc-db59-11e7-8774-d1cf667ffdab.png)

**FireFox** - the content is not visible on first load, but appears on resizing. 
![afbeelding](https://user-images.githubusercontent.com/614243/33717310-b6b78638-db59-11e7-8fc3-134b7f03a346.png)

Could be the static positions of .banner-element__content aren't clear in these browsers...

**Possible solution**
This seems to be solved by adding top/left values to .banner-element__content. something like:

    .banner-element__content {
        position: absolute;
        width: 90%;
        left: 40px; top: 20px; 
    }

(sorry for all that soup)

Martine

**Comment by robbieaverill** [comment]
Thanks for reporting and for investigating! Do you want to make a pull request for the things you've suggested?

**Comment by robbieaverill** [comment]
Testing results:

Bug found: #34 

## Firefox

* Firefox 57 on Windows 7 - initially reproducible when you have a CTA link in your block, while not having a CTA link would render the block correctly. After continued testing I am unable to reproduce the issue at all any more:
![image](https://user-images.githubusercontent.com/5170590/34849423-31404ff4-f787-11e7-865d-24a013e5a63d.png)
* Firefox 58 (beta) on Windows 7 - not reproducible:
![image](https://user-images.githubusercontent.com/5170590/34849363-024931b6-f787-11e7-947a-a3f87e16cd69.png)
* Firefox 57 on macOS (El Capitan & High Sierra) - not reproducible:
![image](https://user-images.githubusercontent.com/5170590/34849707-32517dd6-f788-11e7-9704-2c98cf73c947.png)


## Safari

* Safari 11.0.2 on macOS (High Sierra) - not reproducible:
![image](https://user-images.githubusercontent.com/5170590/34849493-6650eb0e-f787-11e7-98b3-e276c00397ec.png)
* Safari 9.1 on macOS (El Capitan) - **reproducible:**
![image](https://user-images.githubusercontent.com/5170590/34849591-bce0e546-f787-11e7-8a57-b6561e920237.png)


## Internet Explorer

* IE 11 - **reproducible**:
![image](https://user-images.githubusercontent.com/5170590/34849181-62b5bd2c-f786-11e7-8ccf-3d604870e163.png)
* _IE 10 - not supported in SS4_

## Opera

* Opera 50 on Windows 7 - not reproducible:
![image](https://user-images.githubusercontent.com/5170590/34849452-4be28854-f787-11e7-9593-1b9f994711a1.png)
* Opera 50 on macOS (El Capitan) - not reproducible:
![image](https://user-images.githubusercontent.com/5170590/34849730-534bc8a2-f788-11e7-92be-a69f8452d088.png)


## Chrome

* Chrome 63 on Windows 7 - not reproducible:
![image](https://user-images.githubusercontent.com/5170590/34849480-5eb30094-f787-11e7-92b8-24bb0459b59b.png)

---

In cases where this bug is reproducible, the suggested fix works correctly. Since the default stylesheet that this module ships with for the frontend is designed as to be used only as an example, this seems like an acceptable change to add in. I'll make a PR for it.

Thanks for reporting @Martimiz!
